# Generated by Django 6.0.3 on 2026-03-31 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины')),
                ('engine_factory_number', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('transmission_factory_number', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_factory_number', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('steering_axle_factory_number', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.enginemodel', verbose_name='Модель двигателя')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('steering_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.steeringaxlemodel', verbose_name='Модель управляемого моста')),
                ('technique_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.techniquemodel', verbose_name='Модель техники')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.transmissionmodel', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
