# Generated by Django 6.0.3 on 2026-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='supply_contract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Договор поставки №, дата'),
        ),
    ]
