# Generated by Django 6.0.3 on 2026-09-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_supply_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='consignee',
            field=models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
    ]
