# Generated by Django 6.0.3 on 2026-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='downtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='spare_parts',
            field=models.TextField(blank=True, verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='failurenode',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
